# Generated by Django 6.0.2 on 2026-02-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_timecard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeCard',
        ),
    ]
