# Generated by Django 6.0.2 on 2026-02-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_timecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='status',
            field=models.CharField(blank=True, default='Draft', max_length=50),
        ),
        migrations.AddField(
            model_name='timecard',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timecard',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
