# Generated by Django 6.0.2 on 2026-03-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
